# Generated by Django 2.2.19 on 2021-08-27 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_auto_20210815_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
